-- ============================================================
-- 尾上水産 追補マイグレーション 08（Supabase SQL Editor で実行）
-- 目的: マスタ管理（魚種・単価／取引先／餌）を画面から追加・編集・無効化できるよう、
--       DBに正本テーブルを作る。書込は管理者のみ（is_admin）、読取はログイン中ユーザー。
--       ※論理削除方式：active=false で無効化（過去の受注・給餌記録の参照は壊さない）。
-- 前提: 01_security_migration.sql（is_admin/is_active）実行済み。
-- 実行は service_role（SQL Editor既定）で。冪等（何度流してもOK）。
-- ============================================================

-- ── 魚種・単価マスタ ──
create table if not exists public.species_master (
  id          bigint generated by default as identity primary key,
  name        text not null unique,
  price       integer not null default 0,   -- 標準単価 円/kg
  active      boolean not null default true,
  sort_order  integer not null default 0,
  updated_at  timestamptz not null default now()
);

-- ── 取引先マスタ ──
create table if not exists public.buyer_master (
  id          bigint generated by default as identity primary key,
  name        text not null unique,
  category    text not null default '卸業者', -- 区分（卸/小売/ホテル 等）
  contact     text,                            -- 連絡先
  sub_code    text,                            -- 会計 売掛金の補助コード（PCA）
  active      boolean not null default true,
  sort_order  integer not null default 0,
  updated_at  timestamptz not null default now()
);

-- ── 餌マスタ ──
create table if not exists public.feed_master (
  id          bigint generated by default as identity primary key,
  supplier    text,                            -- 仕入先/メーカー
  name        text not null unique,
  price       integer not null default 0,      -- 価格 円/袋
  active      boolean not null default true,
  sort_order  integer not null default 0,
  updated_at  timestamptz not null default now()
);

-- ── RLS：読取=ログイン中(is_active)／書込=管理者(is_admin) ──
alter table public.species_master enable row level security;
alter table public.buyer_master   enable row level security;
alter table public.feed_master    enable row level security;

drop policy if exists species_read  on public.species_master;
drop policy if exists species_admin on public.species_master;
create policy species_read  on public.species_master for select to authenticated using (public.is_active());
create policy species_admin on public.species_master for all    to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists buyer_read  on public.buyer_master;
drop policy if exists buyer_admin on public.buyer_master;
create policy buyer_read  on public.buyer_master for select to authenticated using (public.is_active());
create policy buyer_admin on public.buyer_master for all    to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists feed_read  on public.feed_master;
drop policy if exists feed_admin on public.feed_master;
create policy feed_read  on public.feed_master for select to authenticated using (public.is_active());
create policy feed_admin on public.feed_master for all    to authenticated using (public.is_admin()) with check (public.is_admin());

-- ── GRANT（SQL作成テーブルはAPIに自動公開されないため必須）──
grant select, insert, update, delete on public.species_master to authenticated;
grant select, insert, update, delete on public.buyer_master   to authenticated;
grant select, insert, update, delete on public.feed_master    to authenticated;
grant usage, select on all sequences in schema public to authenticated;

-- ── 初期データ投入（現在ハードコードしている値をシード。既存名はスキップ）──
insert into public.species_master (name, price, sort_order) values
  ('マダイ',1000,1),('カンパチ',2000,2),('シマアジ',1800,3)
on conflict (name) do nothing;

insert into public.buyer_master (name, category, sort_order) values
  ('大海水産','卸業者',1),('脇川水産','卸業者',2),('海水養殖','卸業者',3),
  ('天草漁協（本渡）','卸業者',4),('ニチモウ','卸業者',5),('山家','卸業者',6),
  ('オーシャンプロテック','卸業者',7),('陣内鮮魚店','卸業者',8),('よしやホテル','ホテル',9),
  ('吉中鮮魚店','卸業者',10),('和潮','卸業者',11)
on conflict (name) do nothing;

insert into public.feed_master (supplier, name, price, sort_order) values
  ('坂本飼料','マダイチェリー P9',5050,1),('坂本飼料','マダイチェリー P8',5050,2),
  ('坂本飼料','マダイペレット P7',5530,3),('坂本飼料','ゴールドパワー',4690,4),
  ('伊藤忠飼料','紅40 P6',4780,5),('伊藤忠飼料','紅40 P8',4780,6),
  ('伊藤忠飼料','PBP',0,7),('伊藤忠飼料','インフィニティ',0,8),
  ('ノーサン','Nまだいさくら 6P',5160,9),('ノーサン','Nまだいさくら 8P',5160,10),
  ('ノーサン','Nまだいさくら 10P',5160,11),('ノーサン','Nしまあじ 6P',5760,12),
  ('ノーサン','NKMS マッシュ',5030,13),
  ('ヒガシマル','ひめ桜 S6',6320,14),('ヒガシマル','ひめ桜 S7',6320,15),
  ('ヒガシマル','ひめ桜50 3',5460,16),('ヒガシマル','ひめ桜50 4',5460,17),('ヒガシマル','ひめ桜50 5',5460,18)
on conflict (name) do nothing;

-- ── Realtime（他端末のマスタ変更を即反映したい場合。任意）──
do $$
declare var_tbl text;
begin
  foreach var_tbl in array array['species_master','buyer_master','feed_master'] loop
    if not exists (select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename=var_tbl) then
      execute 'alter publication supabase_realtime add table public.'||var_tbl;
    end if;
  end loop;
end $$;

notify pgrst, 'reload schema';

-- 確認
select 'species' t, count(*) from public.species_master
union all select 'buyer', count(*) from public.buyer_master
union all select 'feed', count(*) from public.feed_master;
