-- ============================================================
-- 尾上水産 追補マイグレーション 09（Supabase SQL Editor で実行）
-- 目的: 日次自動バックアップ＋画面からの復元。
--   ・毎晩 全業務テーブルをJSONで backups 表にスナップショット（pg_cron）
--   ・設定画面から「今すぐバックアップ」「この日に復元」ができる
--   ・保持：直近30日は毎日／それ以前は日曜のみ／120日超は削除
-- 前提: 01（is_admin/is_active）・08（masters）実行済み。
-- 実行は service_role（SQL Editor既定）。冪等。
-- ※ pg_cron はダッシュボード「Database > Extensions」で pg_cron を有効化しておくこと。
-- ============================================================

create extension if not exists pg_cron;

-- ── バックアップ保管テーブル（管理者のみ）──
create table if not exists public.backups (
  id          bigint generated by default as identity primary key,
  taken_at    timestamptz not null default now(),
  label       text default 'auto',
  data        jsonb not null,
  size_bytes  bigint
);
alter table public.backups enable row level security;
drop policy if exists backups_admin on public.backups;
create policy backups_admin on public.backups for all to authenticated
  using (public.is_admin()) with check (public.is_admin());
grant select, insert, update, delete on public.backups to authenticated;
grant usage, select on all sequences in schema public to authenticated;

-- ── スナップショット作成（全業務テーブルをJSON化）──
-- cron(postgres,auth.uid()=null)と管理者のみ許可。保持ルールで自動掃除。
create or replace function public.create_daily_backup(p_label text default 'auto')
returns bigint
language plpgsql security definer set search_path = public as $$
declare snap jsonb; bid bigint;
begin
  if auth.uid() is not null and not public.is_admin() then
    raise exception 'admin only';
  end if;
  snap := jsonb_build_object(
    'ponds',                 (select coalesce(jsonb_agg(to_jsonb(t)),'[]'::jsonb) from public.ponds t),
    'feed_logs',             (select coalesce(jsonb_agg(to_jsonb(t)),'[]'::jsonb) from public.feed_logs t),
    'move_logs',             (select coalesce(jsonb_agg(to_jsonb(t)),'[]'::jsonb) from public.move_logs t),
    'orders',                (select coalesce(jsonb_agg(to_jsonb(t)),'[]'::jsonb) from public.orders t),
    'shipments',             (select coalesce(jsonb_agg(to_jsonb(t)),'[]'::jsonb) from public.shipments t),
    'payments',              (select coalesce(jsonb_agg(to_jsonb(t)),'[]'::jsonb) from public.payments t),
    'inventory_adjustments', (select coalesce(jsonb_agg(to_jsonb(t)),'[]'::jsonb) from public.inventory_adjustments t),
    'species_master',        (select coalesce(jsonb_agg(to_jsonb(t)),'[]'::jsonb) from public.species_master t),
    'buyer_master',          (select coalesce(jsonb_agg(to_jsonb(t)),'[]'::jsonb) from public.buyer_master t),
    'feed_master',           (select coalesce(jsonb_agg(to_jsonb(t)),'[]'::jsonb) from public.feed_master t)
  );
  insert into public.backups(label, data, size_bytes)
    values (coalesce(p_label,'auto'), snap, octet_length(snap::text))
    returning id into bid;
  -- 保持ルール
  delete from public.backups b
    where b.taken_at < now() - interval '30 days'
      and extract(dow from b.taken_at) <> 0;      -- 30日超は日曜以外を削除
  delete from public.backups where taken_at < now() - interval '120 days';
  return bid;
end $$;

-- ── 復元（指定バックアップの内容で全テーブルを置き換え。1トランザクション＝失敗時は自動ロールバック）──
create or replace function public.restore_backup(p_id bigint)
returns void
language plpgsql security definer set search_path = public as $$
declare snap jsonb;
begin
  if not public.is_admin() then raise exception 'admin only'; end if;
  select data into snap from public.backups where id = p_id;
  if snap is null then raise exception 'backup % not found', p_id; end if;

  set local session_replication_role = replica;   -- 復元中はFK/トリガを一時停止

  delete from public.species_master;
  insert into public.species_master select * from jsonb_populate_recordset(null::public.species_master, snap->'species_master');
  delete from public.buyer_master;
  insert into public.buyer_master select * from jsonb_populate_recordset(null::public.buyer_master, snap->'buyer_master');
  delete from public.feed_master;
  insert into public.feed_master select * from jsonb_populate_recordset(null::public.feed_master, snap->'feed_master');
  delete from public.ponds;
  insert into public.ponds select * from jsonb_populate_recordset(null::public.ponds, snap->'ponds');
  delete from public.shipments;
  insert into public.shipments select * from jsonb_populate_recordset(null::public.shipments, snap->'shipments');
  delete from public.orders;
  insert into public.orders select * from jsonb_populate_recordset(null::public.orders, snap->'orders');
  delete from public.feed_logs;
  insert into public.feed_logs select * from jsonb_populate_recordset(null::public.feed_logs, snap->'feed_logs');
  delete from public.move_logs;
  insert into public.move_logs select * from jsonb_populate_recordset(null::public.move_logs, snap->'move_logs');
  delete from public.inventory_adjustments;
  insert into public.inventory_adjustments select * from jsonb_populate_recordset(null::public.inventory_adjustments, snap->'inventory_adjustments');
  delete from public.payments;
  insert into public.payments select * from jsonb_populate_recordset(null::public.payments, snap->'payments');

  set local session_replication_role = default;
end $$;

-- RPC公開範囲：anonは不可、authenticatedのみ（中で管理者判定）
revoke all on function public.create_daily_backup(text) from public, anon;
revoke all on function public.restore_backup(bigint)    from public, anon;
grant execute on function public.create_daily_backup(text) to authenticated;
grant execute on function public.restore_backup(bigint)    to authenticated;

-- ── 毎晩 00:00 JST（=15:00 UTC）に自動バックアップ ──
select cron.unschedule('onoue-daily-backup')
  where exists (select 1 from cron.job where jobname='onoue-daily-backup');
select cron.schedule('onoue-daily-backup', '0 15 * * *', $$ select public.create_daily_backup('auto'); $$);

-- 初回スナップショットを1件作成（動作確認）
select public.create_daily_backup('初回');
notify pgrst, 'reload schema';
select id, taken_at, label, size_bytes from public.backups order by id desc limit 3;
