-- ============================================================
-- 尾上水産 追補マイグレーション 10（Supabase SQL Editor で実行）
-- 目的: 薬マスタ・生餌マスタ（価格つき）を追加。08と同じ方式（RLS=読取:ログイン/書込:管理者）。
-- 前提: 01（is_admin/is_active）実行済み。冪等。
-- ============================================================

create table if not exists public.drug_master (
  id bigint generated by default as identity primary key,
  name text not null unique,
  price integer not null default 0,   -- 価格
  unit  text default '円',            -- 単位（円/g・円/本 など）
  active boolean not null default true,
  sort_order integer not null default 0,
  updated_at timestamptz not null default now()
);
create table if not exists public.live_esa_master (
  id bigint generated by default as identity primary key,
  name text not null unique,
  price integer not null default 0,   -- 価格
  unit  text default '円/kg',
  active boolean not null default true,
  sort_order integer not null default 0,
  updated_at timestamptz not null default now()
);

alter table public.drug_master     enable row level security;
alter table public.live_esa_master enable row level security;

drop policy if exists drug_read  on public.drug_master;
drop policy if exists drug_admin on public.drug_master;
create policy drug_read  on public.drug_master for select to authenticated using (public.is_active());
create policy drug_admin on public.drug_master for all    to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists live_read  on public.live_esa_master;
drop policy if exists live_admin on public.live_esa_master;
create policy live_read  on public.live_esa_master for select to authenticated using (public.is_active());
create policy live_admin on public.live_esa_master for all    to authenticated using (public.is_admin()) with check (public.is_admin());

grant select, insert, update, delete on public.drug_master     to authenticated;
grant select, insert, update, delete on public.live_esa_master to authenticated;
grant usage, select on all sequences in schema public to authenticated;

-- 初期データ（価格は0＝後で画面から入力。現在アプリに入っている品目をシード）
insert into public.drug_master (name, unit, sort_order) values
  ('オキシテトラサイクリン','円',1),('フロルフェニコール','円',2),('スルファモノメトキシン','円',3),
  ('エンロフロキサシン','円',4),('プラジクアンテル','円',5),('トリクロルホン','円',6),
  ('マラカイトグリーン','円',7),('ホルマリン','円',8),('その他','円',9)
on conflict (name) do nothing;

insert into public.live_esa_master (name, unit, sort_order) values
  ('イワシ','円/kg',1),('サバ','円/kg',2),('さんま','円/kg',3)
on conflict (name) do nothing;

-- Realtime（任意）
do $$
declare var_tbl text;
begin
  foreach var_tbl in array array['drug_master','live_esa_master'] loop
    if not exists (select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename=var_tbl) then
      execute 'alter publication supabase_realtime add table public.'||var_tbl;
    end if;
  end loop;
end $$;

notify pgrst, 'reload schema';
select 'drug' t, count(*) from public.drug_master
union all select 'live', count(*) from public.live_esa_master;
